### PR TITLE
Fix Plugin ClassCastException

### LINKED ISSUE #7: IntelliJ Plugin: ClassCastException
**Repro steps or stacktrace**:

```
java.lang.ClassCastException: com.intellij.psi.PsiPrimitiveType cannot be cast to com.intellij.psi.PsiClassType
	at motif.intellij.graph.GraphProcessor.getClass(GraphProcessor.kt:81)
	at motif.intellij.MotifScopeLineMarkerProvider.collectNavigationMarkers(MotifScopeLineMarkerProvider.kt:59)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectNavigationMarkers(RelatedItemLineMarkerProvider.java:49)
	at com.intellij.codeInsight.daemon.RelatedItemLineMarkerProvider.collectSlowLineMarkers(RelatedItemLineMarkerProvider.java:40)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:197)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:104)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1151)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### PR DESCRIPTION
**Pull request by cryptogrammer**
Fix ClassCastException in the plugin by ensuring correct type casting. Fixes #7

### CODE REVIEW

File: plugin/src/main/kotlin/motif/intellij/graph/GraphProcessor.kt [hunk 1]
```diff
@@ -45,8 +45,8 @@ class GraphProcessor(private val project: Project) {
         return scopeClasses
                 .flatMap { scopeClass ->
                     scopeClass.methods
-                            .filter { it.returnType != null }
-                            .map { ScopeMethod(scopeClass, it.returnType!!.getClass()) }
+                            .filter { it.returnType != null && it.returnType!!.getClass() != null}
```
Comment (Leland-Takamine) [inline plugin/src/main/kotlin/motif/intellij/graph/GraphProcessor.kt]:
```kotlin
.mapNotNull { it.returnType?.getClass() }
.map { ScopeMethod(scopeClass, it) }
```
